"use client";
import {useState} from 'react';
import {Eye,EyeOff} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
export function Choice({label,value,onChange,options}:any){return <label className="field"><span>{label}</span><Select value={value||'all'} onValueChange={onChange}><SelectTrigger className="select-control"><SelectValue/></SelectTrigger><SelectContent>{options.map((o:any)=><SelectItem key={typeof o==='string'?o:o.value} value={typeof o==='string'?o:o.value}>{typeof o==='string'?o:o.label}</SelectItem>)}</SelectContent></Select></label>}
export function Form({fields,initial={},submit='Salvar',onSubmit,beforeSubmit}:any){const [values,setValues]=useState<any>(()=>({...Object.fromEntries(fields.filter((f:any)=>f.options).map((f:any)=>[f.key,f.options[0]])),...initial})),[error,setError]=useState(''),[busy,setBusy]=useState(false),[visible,setVisible]=useState<Record<string,boolean>>({});const change=(k:string,v:any)=>setValues((s:any)=>({...s,[k]:v}));return <form className="form" onSubmit={async e=>{e.preventDefault();const submitted={...values,...Object.fromEntries(new FormData(e.currentTarget).entries())};setError('');if(submitted.confirm!==undefined&&submitted.password!==submitted.confirm){setError('As senhas precisam ser iguais.');return}setBusy(true);try{await onSubmit(submitted)}catch(e:any){setError(e.message||'Não foi possível salvar. Tente novamente.')}finally{setBusy(false)}}}>{fields.map((f:any)=>f.options?<Choice key={f.key} label={f.label} value={values[f.key]||f.options[0]} options={f.options} onChange={(v:any)=>change(f.key,v)}/>:<label className="field" key={f.key}><span>{f.label}{f.optional?' (opcional)':''}</span>{f.type==='textarea'?<textarea name={f.key} required={!f.optional} value={values[f.key]||''} onChange={e=>change(f.key,e.target.value)} rows={4}/>:f.type==='file'?<input type="file" accept="image/*" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>2000000){setError('Escolha uma imagem de até 2 MB.');return}const r=new FileReader();r.onload=()=>change(f.key,r.result);r.readAsDataURL(file)}}/>:<div className="input-wrap"><input name={f.key} type={f.type==='password'&&visible[f.key]?'text':f.type||'text'} required={!f.optional} min={f.type==='number'?1:undefined} minLength={f.type==='password'?6:undefined} value={values[f.key]||''} onChange={e=>change(f.key,e.target.value)} autoComplete={f.type==='password'?'new-password':f.key==='email'?'email':undefined}/>{f.type==='password'&&<button type="button" className="password-toggle" aria-label={(visible[f.key]?'Ocultar ':'Mostrar ')+f.label.toLowerCase()} onClick={()=>setVisible(v=>({...v,[f.key]:!v[f.key]}))}>{visible[f.key]?<EyeOff size={18}/>:<Eye size={18}/>}</button>}</div>}</label>)}{beforeSubmit}{error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={busy}>{busy?'Salvando…':submit}</button></form>}
export const field=(key:string,label:string,type='text',optional=false)=>({key,label,type,optional});


