"use client";
import {useEffect,useState} from 'react';
import {Heart,Search,HandHeart,UserRound,Bell,MapPin,CalendarDays,Check,Building2,Plus,LogOut,ChevronRight,Sprout,LockKeyhole,Camera,Users,Copy} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {Switch} from '@/components/ui/switch';
import {toast} from 'sonner';
import {seed,repository,categories} from './data';
import {money,date} from './utils/formatters';
import {Form,Choice,field} from './forms';
import {authenticate,accountHome,allowedAccountRoute} from './auth';
import {Checkbox} from '@/components/ui/checkbox';
import {OrganizationIdentity,OrganizationCard,OpportunityCard,FilterChips,ImpactStrip,DonationHistoryCard,NoticeCard,donationCode} from './user-ui';
import {useHashRoute,go} from './hooks/use-hash-route';
import {empty,link,title} from './components/common/page-elements';
import {AppShell} from './components/layout/app-shell';
export default function App(){
 const route=useHashRoute();
 const [db,setDb]=useState<any>(seed),[ready,setReady]=useState(false),[query,setQuery]=useState(''),[city,setCity]=useState('all'),[district,setDistrict]=useState('all'),[cat,setCat]=useState('all'),[day,setDay]=useState(''),[amount,setAmount]=useState('50'),[step,setStep]=useState(1),[draft,setDraft]=useState<any>({}),[activityStatus,setActivityStatus]=useState('all'),[noticeType,setNoticeType]=useState('all'),[remember,setRemember]=useState(true),[checkout,setCheckout]=useState<any>(null),[completedDonation,setCompletedDonation]=useState<any>(null);
 useEffect(()=>{setDb(repository.load());try{setCheckout(JSON.parse(sessionStorage.getItem('setho-checkout')||'null'))}catch{}setReady(true)},[]);
 useEffect(()=>{setQuery('');setCity('all');setDistrict('all');setCat('all');setDay('')},[route]);
 const update=(fn:any)=>{setDb((previous:any)=>{const next=fn(structuredClone(previous));try{repository.save(next)}catch{toast.error('O armazenamento está cheio. Use uma imagem menor.');return previous}return next})};
 useEffect(()=>{if(!db.session)return;const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const life=new AbortController();Promise.resolve(ctx.registerTool({name:'search_setho_organizations',description:'Busca ONGs cadastradas no SETHO, sem alterar dados.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true},execute:({query}:any)=>{if(typeof query!=='string')throw Error('Busca inválida');return db.orgs.filter((o:any)=>o.name.toLowerCase().includes(query.toLowerCase())).map(({id,name,city,category}:any)=>({id,name,city,category}))}},{signal:life.signal})).catch(()=>{});return()=>life.abort()},[db.orgs,db.session?.role]);
 const user=db.session,admin=user?.role==='ong',own=db.orgs.find((o:any)=>o.id===user?.org),[page,id,arg]=route.split('/');
 const org=db.orgs.find((o:any)=>o.id===id),orgName=(id:string)=>db.orgs.find((o:any)=>o.id===id)?.name||'ONG';
 useEffect(()=>{if(!ready)return;if(!user){if(!['','entrar','cadastro','cadastro-ong','recuperar','tenho-ong'].includes(location.hash.replace(/^#\/?/,'').split('/')[0]))go('entrar');return}const target=allowedAccountRoute(route,user.role);if(target!==route)go(target)},[ready,route,user?.role]);
 const mineDon=db.donations.filter((d:any)=>d.user===user?.id),mineReg=db.registrations.filter((r:any)=>r.user===user?.id);
 const notify=(d:any,text:string,owner:string)=>{if(d.accounts.find((a:any)=>a.id===owner)?.notifications===false||(d.session?.id===owner&&d.session.notifications===false))return;d.notifications.unshift({id:crypto.randomUUID(),text,owner,read:false,date:new Date().toLocaleDateString('pt-BR')})};
 const requireLogin=(_target:string)=>{if(!user||admin){if(admin)toast.info('Entre com uma conta de usuário para doar ou se voluntariar.');go('entrar');return false}return true};
 const finishLogin=(account:any)=>{update((d:any)=>{d.session={...account,remember};return d});sessionStorage.removeItem('setho-return');go(accountHome(account.role))};
 const demo=(role:string)=>{const account=db.accounts.find((a:any)=>a.id===(role==='ong'?'demo-ong':'demo-user'));if(account)finishLogin(account)};
 const stats=(items:any[]) => <div className="stats">{items.map(([v,l])=><div key={l}><b>{v}</b><span>{l}</span></div>)}</div>;
 const cards=(list:any[],compact=false)=>list.length?<div className="responsive-card-grid">{list.map((o:any)=><OrganizationCard key={o.id} org={o} compact={compact} favorite={db.favorites.includes(o.id)} onFavorite={()=>update((d:any)=>{d.favorites=d.favorites.includes(o.id)?d.favorites.filter((x:string)=>x!==o.id):[...d.favorites,o.id];return d})}/>)}</div>:empty('Nenhuma ONG encontrada');
 const opportunities=(list:any[])=>list.length?<div className="responsive-card-grid">{list.map((v:any)=><OpportunityCard key={v.id} item={v} org={db.orgs.find((o:any)=>o.id===v.org)} available={Math.max(0,Number(v.slots)-db.registrations.filter((r:any)=>r.opportunity===v.id).length)}/>)}</div>:empty('Nenhuma oportunidade encontrada');
 const funding=(list:any[],type:string,detail=false)=>list.length?<div className={detail?'':'responsive-card-grid'}>{list.map((n:any)=><article className="card" key={n.id}><span className="tag">{n.status}</span><h2>{n.title}</h2>{n.image&&n.image!=='/setho.jpeg'&&<img className="content-image" src={n.image} alt={n.title}/>}<p>{n.description}</p><div className="between"><b>{money(Number(n.raised))}</b><small>de {money(Number(n.goal))}</small></div><Progress value={Math.min(100,n.raised/n.goal*100)} className="fund-progress"/><div className="between"><small>{Math.round(n.raised/n.goal*100)}% alcançado</small><small>Até {date(n.deadline)}</small></div>{!detail&&link((type==='projects'?'projeto/':'necessidade/')+n.id,type==='projects'?'Ver projeto':'Quero ajudar','secondary')}{admin&&n.org===own?.id&&link('editar/'+type+'/'+n.id,'Editar '+(type==='projects'?'projeto':'necessidade'),'secondary')}</article>)}</div>:empty('Nenhum cadastro por enquanto');
 const filters=(vol=false)=><div className="compact-filters"><label className="search"><Search size={18}/><input aria-label="Buscar" placeholder={vol?'Buscar oportunidade...':'Buscar ONG...'} value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="filter-grid"><Choice label="Cidade" value={city} onChange={(v:string)=>{setCity(v);setDistrict('all')}} options={[{value:'all',label:'Cidade'},...Array.from(new Set(db.orgs.map((o:any)=>o.city)))]}/><Choice label="Bairro" value={district} onChange={setDistrict} options={[{value:'all',label:'Bairro'},...Array.from(new Set(db.orgs.filter((o:any)=>city==='all'||o.city===city).map((o:any)=>o.district)))]}/><Choice label="Categoria" value={cat} onChange={setCat} options={[{value:'all',label:'Categoria'},...categories]}/></div>{vol?<label className="field date-filter"><span><CalendarDays size={14}/> Filtrar por data</span><input type="date" aria-label="Data do voluntariado" value={day} onChange={e=>setDay(e.target.value)}/></label>:<FilterChips label="Causas" value={cat} onChange={setCat} items={[{value:'all',label:'Todas'},...categories.map(c=>({value:c,label:c}))]}/ >}{(query||city!=='all'||district!=='all'||cat!=='all'||day)&&<button className="text-button" onClick={()=>{setQuery('');setCity('all');setDistrict('all');setCat('all');setDay('')}}>Limpar filtros</button>}</div>;
 const match=(o:any)=>o&&(city==='all'||o.city===city)&&(district==='all'||o.district===district)&&(cat==='all'||o.category===cat);
 const history=(list:any[])=>list.length?<div className="responsive-card-grid">{list.map((d:any)=>!admin?<DonationHistoryCard key={d.id} donation={d} org={db.orgs.find((o:any)=>o.id===d.org)} money={money}/>:<div className="card" key={d.id}><div className="between"><b>{orgName(d.org)}</b><b>{money(d.amount)}</b></div><p>{d.targetTitle||'Apoio à organização'}</p><small>{d.date} · Confirmada · Simulação</small></div>)}</div>:empty('Nenhuma doação por enquanto');
 let body:any;
 const publicPages=['','entrar','cadastro','cadastro-ong','recuperar','tenho-ong'];
 if(!user&&!publicPages.includes(page)){body=<>{title('Entre para continuar','Acesse sua conta para fazer parte da comunidade SETHO.')}{link('entrar','Entrar')}{link('','Conhecer o SETHO','secondary')}</>}
 else if(!page){body=<><section className="welcome-hero"><h1>Juntos podemos<br/>transformar<br/>realidades.</h1><p>Encontre ONGs, apoie projetos,<br/>faça uma doação ou ofereça seu<br/>tempo como voluntário.</p><img className="welcome-photo" src="/community.jpg" alt="Voluntários plantando uma muda em comunidade"/><div className="welcome-actions">{link(user?'ongs':'entrar','Quero ajudar')}{link(user?'tenho-ong':'entrar','Tenho uma ONG','secondary')}</div></section><section className="about-setho"><h2>O bem cresce quando a gente se une.</h2><p>O SETHO conecta pessoas e organizações para construir um futuro melhor, um gesto de cada vez.</p><h2>Como funciona</h2>{['Encontre uma ONG','Conheça sua causa','Escolha como ajudar','Faça parte da transformação'].map((x,i)=><div className="step" key={x}><span>0{i+1}</span><b>{x}</b></div>)}</section><section><h2>Você pode ajudar de várias formas</h2><div className="ways">{[[Heart,'Doar','Cada gesto conta.'],[HandHeart,'Oferecer tempo','Seu tempo transforma.'],[Sprout,'Apoiar projetos','Cultive uma causa.']].map(([Icon,t,sub]:any)=><div key={t}><Icon size={23}/><b>{t}</b><small>{sub}</small></div>)}</div></section></>}
 else if(page==='ongs'){const list=db.orgs.filter((o:any)=>match(o)&&(o.name+' '+o.description).toLowerCase().includes(query.toLowerCase()));body=<>{title('Encontre uma ONG')}{filters()}<small className="result-count">{list.length} organizações encontradas</small>{cards(list)}</>}
 else if(page==='voluntariado'){const list=db.opportunities.filter((v:any)=>(!id||v.org===id)&&match({...db.orgs.find((o:any)=>o.id===v.org),category:v.category})&&(!day||v.date===day)&&(v.title+' '+orgName(v.org)).toLowerCase().includes(query.toLowerCase()));body=<>{title('Voluntariado')}{filters(true)}{opportunities(list)}</>}
 else if(page==='ong'&&org){body=<><div className="cause-cover"><img src={org.cover||'/community.jpg'} alt="Pessoas colaborando em uma ação comunitária"/></div><OrganizationIdentity org={org}/><p className="cause-intro">{org.description}</p><Tabs defaultValue="sobre"><TabsList className="ong-tabs">{['Sobre','Necessidades','Projetos','Voluntariado'].map(t=><TabsTrigger key={t} value={t.toLowerCase()}>{t}</TabsTrigger>)}</TabsList><div className="cause-actions">{link('doar/'+id,<><Heart size={18}/>Doar</>)}{link('voluntariado/'+id,'Quero ser voluntário','secondary')}</div><TabsContent value="sobre"><h2>Sobre a ONG</h2><p>{org.history}</p><h3>Nossa missão</h3><p>{org.mission}</p><div className="values-line"><Sprout size={20}/><span>Respeito, solidariedade, inclusão e esperança.</span></div></TabsContent><TabsContent value="necessidades">{funding(db.needs.filter((n:any)=>n.org===id),'needs')}</TabsContent><TabsContent value="projetos">{funding(db.projects.filter((n:any)=>n.org===id),'projects')}</TabsContent><TabsContent value="voluntariado">{opportunities(db.opportunities.filter((n:any)=>n.org===id))}</TabsContent></Tabs></>}
 else if(page==='projetos'){body=<>{title('Projetos que fazem crescer','Apoie uma transformação desde a raiz.')}{funding(db.projects,'projects')}</>}
 else if(page==='projeto'||page==='necessidade'){const n=db[page==='projeto'?'projects':'needs'].find((n:any)=>n.id===id);body=n?<><span className="tag">{orgName(n.org)}</span>{title(n.title)}{funding([n],page==='projeto'?'projects':'needs',true)}<h2>Objetivo</h2><p>{n.objective||n.description}</p>{n.audience&&<p>Público beneficiado: {n.audience}</p>}{link('doar/'+n.org+'/'+n.id,'Contribuir agora')}</>:empty('Cadastro não encontrado')}
 else if(page==='doar'&&org){const target=[...db.needs,...db.projects].find((n:any)=>n.id===arg);body=<>{title('Fazer uma doação')}<div className="selected-organization"><OrganizationIdentity org={org} small/></div><h2>Escolha o valor</h2><div className="donation-amounts">{[25,50,100,200].map(v=><button className={amount===String(v)?'selected':''} onClick={()=>setAmount(String(v))} key={v}>{money(v).replace(',00','')}</button>)}<label className="custom-amount"><span>Outro valor</span><input type="number" aria-label="Outro valor em reais" min="1" step="0.01" placeholder="R$" value={[25,50,100,200].includes(Number(amount))?'':amount} onChange={e=>setAmount(e.target.value)}/></label></div><h2>Resumo da doação</h2><div className="donation-summary"><div><Building2/><span><small>ONG</small>{org.name}</span></div><div><MapPin/><span><small>Projeto/necessidade</small>{target?.title||'Apoio à organização'}</span></div><div><Heart/><span><small>Valor</small><b>{money(Number(amount)||0)}</b></span></div></div><button className="primary" onClick={()=>{const value=Number(amount);if(!Number.isFinite(value)||value<1){toast.error('Informe um valor de pelo menos R$ 1.');return}if(!requireLogin(route))return;const pending={id:crypto.randomUUID(),org:id,user:user.id,amount:Math.round(value*100)/100,target:arg,targetTitle:target?.title};setCheckout(pending);sessionStorage.setItem('setho-checkout',JSON.stringify(pending));go('pix')}}>Continuar</button><p className="note">Doação simulada. Nenhuma cobrança será feita.</p></>}
 else if(page==='pix'){const paymentOrg=db.orgs.find((o:any)=>o.id===checkout?.org);body=checkout&&paymentOrg&&checkout.user===user?.id?<>{title('Pagamento via Pix')}<div className="pix-card"><OrganizationIdentity org={paymentOrg} small/><div className="pix-value"><small>Valor da doação</small><b>{money(checkout.amount)}</b></div><img className="pix-qr" src="/demo-qr.svg" alt="QR Code de demonstração, sem valor de pagamento"/><span className="pix-caption">Pix demonstrativo</span><code>{donationCode}</code><button className="primary" onClick={async()=>{try{await navigator.clipboard.writeText(donationCode);toast.success('Código de demonstração copiado')}catch{toast.error('Não foi possível copiar. Selecione o código acima.')}}}><Copy size={16}/>Copiar código Pix (mock)</button><p className="note">Este é um Pix de demonstração.<br/>Não realize pagamentos reais.</p></div><button className="primary" onClick={()=>{if(!requireLogin(route))return;const payment={...checkout,date:new Date().toLocaleDateString('pt-BR')};update((d:any)=>{if(d.donations.some((x:any)=>x.id===payment.id))return d;d.donations.unshift(payment);const n=[...d.needs,...d.projects].find((n:any)=>n.id===payment.target);if(n)n.raised=Number(n.raised)+payment.amount;notify(d,'Sua doação de '+money(payment.amount)+' para '+paymentOrg.name+' foi confirmada.',user.id);notify(d,'Nova doação de '+money(payment.amount),paymentOrg.id);if(n&&n.raised>=n.goal)notify(d,n.title+' atingiu a meta.',paymentOrg.id);return d});setCompletedDonation(payment);setCheckout(null);sessionStorage.removeItem('setho-checkout');go('sucesso/doacao')}}>Simular pagamento</button></>:<>{title('Vamos escolher uma causa?','Selecione uma ONG e o valor para iniciar a demonstração.')}{link('ongs','Encontrar uma ONG')}</>}
 else if(page==='oportunidade'){const v=db.opportunities.find((v:any)=>v.id===id),count=db.registrations.filter((r:any)=>r.opportunity===id).length,joined=mineReg.some((r:any)=>r.opportunity===id),vo=db.orgs.find((o:any)=>o.id===v?.org);body=v&&vo?<><div className="cause-cover"><img src={v.image||vo.cover||'/community.jpg'} alt="Ação de voluntariado na comunidade"/></div><OrganizationIdentity org={vo}/>{title(v.title)}<div className="opportunity-facts"><p><CalendarDays size={19}/>{date(v.date)}<span>·</span>{v.time}</p><p><MapPin size={19}/>{v.location}</p><p><Users size={19}/>{Math.max(0,v.slots-count)} vagas disponíveis</p></div><p>{v.description}</p><h2>Requisitos</h2><ul className="requirements">{v.requirements.split('. ').filter(Boolean).map((r:string)=><li key={r}>{r}</li>)}</ul><button className="primary" disabled={joined||count>=Number(v.slots)} onClick={()=>{if(!requireLogin(route))return;update((d:any)=>{if(d.registrations.some((r:any)=>r.opportunity===id&&r.user===user.id))return d;d.registrations.push({id:crypto.randomUUID(),user:user.id,name:user.name,opportunity:id,org:v.org,date:new Date().toLocaleDateString('pt-BR'),status:'Inscrito'});notify(d,'Voluntariado confirmado: '+v.title,user.id);notify(d,'Novo voluntário: '+user.name,v.org);return d});go('sucesso/voluntariado')}}>{joined?'Você já está inscrito':count>=v.slots?'Vagas preenchidas':'Quero me voluntariar'}</button></>:empty('Oportunidade não encontrada')}
 else if(page==='sucesso'&&id==='doacao'&&completedDonation){const receiptOrg=db.orgs.find((o:any)=>o.id===completedDonation.org);body=<div className="success donation-success"><div className="check"><Check size={49}/></div>{title('Doação realizada! ❤️','Obrigado por fazer parte dessa transformação.')}<div className="receipt-card"><OrganizationIdentity org={receiptOrg} small/><b className="receipt-amount">{money(completedDonation.amount)}</b><p>{completedDonation.targetTitle||'Apoio à organização'}</p><small>Confirmada · Simulação</small></div>{link('ongs','Voltar para ONGs')}{link('doacoes','Ver minhas doações','text-link')}</div>}
 else if(page==='sucesso'){const opts:any={doacao:['Doação realizada!','Obrigado por fazer parte dessa transformação.','ongs','Voltar para ONGs'],voluntariado:['Você está inscrito!','Obrigado por oferecer seu tempo para ajudar.','meus-voluntariados','Ver meus voluntariados'],ong:['ONG cadastrada com sucesso!','Agora você pode cadastrar projetos, necessidades e oportunidades de voluntariado.','painel','Ir para o painel']};const o=opts[id!]||opts.doacao;body=<div className="success"><div className="check"><Check size={42}/></div>{title(o[0],o[1])}{link(o[2],o[3])}</div>}
 else if(page==='entrar'){body=<><img className="auth-logo" src="/setho.jpeg" alt="SETHO"/>{title('Entrar na sua conta')}<Form key={route} submit="Entrar" fields={[field('email','E-mail','email'),field('password','Senha','password')]} beforeSubmit={<div className="login-options"><label><Checkbox checked={remember} onCheckedChange={v=>setRemember(v===true)}/>Lembrar de mim</label><a href="#/recuperar">Esqueci minha senha</a></div>} onSubmit={async(v:any)=>{finishLogin(authenticate(db.accounts,v.email,v.password))}}/><div className="or-divider"><span>ou</span></div>{link('cadastro','Criar conta','secondary')}{link('cadastro-ong','Cadastrar minha ONG','text-link')}<details className="demo-access"><summary>Conhecer com uma conta de demonstração</summary><p>Usuário: usuario@setho.com<br/>ONG: ong@setho.com<br/>Senha: 123456</p><button className="secondary" onClick={()=>demo('user')}>Explorar como usuário</button><button className="secondary" onClick={()=>demo('ong')}>Explorar como ONG</button></details><p className="note">Demonstração local. Use uma senha fictícia.</p></>}
 else if(page==='cadastro'){body=<>{title('Criar conta de usuário')}<Form key={route} submit="Criar conta" fields={[field('name','Nome'),field('email','E-mail','email'),field('city','Cidade'),field('password','Senha','password'),field('confirm','Confirmar senha','password')]} onSubmit={async(v:any)=>{if(db.accounts.some((a:any)=>a.email.toLowerCase()===v.email.toLowerCase()))throw Error('Este e-mail já está cadastrado.');const a={...v,id:crypto.randomUUID(),role:'user'};update((d:any)=>{d.accounts.push(a);return d});finishLogin(a)}}/><p className="note">Cadastro simulado neste navegador. Use uma senha fictícia.</p>{link('entrar','Já tenho uma conta','text-link')}</>}
 else if(page==='recuperar'){body=<>{title('Recuperar acesso','Na demonstração, você pode redefinir sua senha local pelo e-mail cadastrado.')}<Form key={route} submit="Redefinir senha local" fields={[field('email','E-mail cadastrado','email'),field('password','Nova senha fictícia','password'),field('confirm','Confirmar nova senha','password')]} onSubmit={async(v:any)=>{if(!db.accounts.some((a:any)=>a.email===v.email))throw Error('Não encontramos essa conta neste navegador.');update((d:any)=>{d.accounts.find((a:any)=>a.email===v.email).password=v.password;return d});toast.success('Senha local atualizada');go('entrar')}}/></>}
 else if(page==='tenho-ong'){body=<><span className="eyebrow"><Building2 size={18}/> PARA ORGANIZAÇÕES</span>{title('Faça sua ONG fazer parte do SETHO','Cadastre sua organização, apresente seu trabalho, receba doações e encontre pessoas dispostas a contribuir com sua causa.')}<img className="auth-logo" src="/setho.jpeg" alt="SETHO"/>{['Receba doações','Divulgue seus projetos','Encontre voluntários','Cadastre suas necessidades'].map(t=><div className="step" key={t}><Check size={20}/><b>{t}</b></div>)}{link('cadastro-ong','Cadastrar minha ONG')}{link('entrar','Minha ONG já está cadastrada','text-link')}</>}
 else if(page==='cadastro-ong'){const fields=[ [field('name','Nome da ONG'),field('cnpj','CNPJ'),{key:'category',label:'Área de atuação',options:categories},field('institutionEmail','E-mail institucional','email'),field('phone','Telefone','tel')], [field('state','Estado'),field('city','Cidade'),field('district','Bairro'),field('address','Endereço')], [field('history','História','textarea'),field('description','Descrição','textarea'),field('mission','Missão','textarea'),field('mainNeeds','Principais necessidades','textarea'),field('image','Logo/foto','file',true)], [field('responsible','Nome do responsável'),field('email','E-mail','email'),field('password','Senha','password'),field('confirm','Confirmar senha','password')] ];body=<>{title('Cadastrar minha ONG')}<div className="between"><b>{['Dados da organização','Localização','Sobre a organização','Responsável'][step-1]}</b><small>{step} de 4</small></div><Progress value={step*25} className="fund-progress"/><Form key={step} fields={fields[step-1]} initial={draft} submit={step===4?'Cadastrar ONG':'Continuar'} onSubmit={async(v:any)=>{const next={...draft,...v};if(step===1&&next.cnpj.replace(/\D/g,'').length!==14)throw Error('Informe um CNPJ com 14 dígitos.');setDraft(next);if(step<4){setStep(step+1);window.scrollTo(0,0);return}if(db.accounts.some((a:any)=>a.email===next.email))throw Error('E-mail já cadastrado.');const oid=crypto.randomUUID(),a={id:crypto.randomUUID(),role:'ong',org:oid,name:next.responsible,email:next.email,password:next.password,city:next.city};update((d:any)=>{d.orgs.push({...next,id:oid,image:next.image||'/setho.jpeg'});d.accounts.push(a);d.session=a;return d});setStep(1);setDraft({});go('sucesso/ong')}}/>{step>1&&<button className="text-button" onClick={()=>setStep(step-1)}>Voltar à etapa anterior</button>}<p className="note">Cadastro local de demonstração.</p></>}
 else if(!user&&['inicio','doacoes','meus-voluntariados','perfil','editar-perfil','senha','painel','minha-ong','gerenciar','novo','editar','editar-ong','notificacoes','recebidas','inscritos'].includes(page)){body=<div className="success"><UserRound size={44}/>{title('Faça parte dessa comunidade.','Entre para acompanhar suas doações, inscrições e sua organização.')}{link('entrar','Entrar')}{link('cadastro','Criar conta','secondary')}</div>}
 else if(page==='inicio'){body=<><section className="user-welcome"><h1>Olá, {user.name.split(' ')[0]}! <span>👋</span></h1><p>Como você quer ajudar hoje?</p><div className="quick-help">{[[MapPin,'Encontrar uma ONG','ongs'],[HandHeart,'Quero voluntariar','voluntariado'],[Heart,'Fazer uma doação','ongs']].map(([Icon,t,p]:any)=><a href={'#/'+p} key={t}><span><Icon size={25} fill={t==='Fazer uma doação'?'currentColor':'none'}/></span><b>{t}</b></a>)}</div></section><section><h2>Seu impacto</h2><ImpactStrip items={[[money(mineDon.reduce((a:number,d:any)=>a+d.amount,0)),'Total doado'],[new Set(mineDon.map((d:any)=>d.org)).size,'ONGs apoiadas'],[mineReg.length,'Voluntariados']]}/></section><section><div className="section-heading"><h2>ONGs em destaque</h2><a href="#/ongs">Ver todas <ChevronRight size={14}/></a></div>{cards(db.orgs.slice(0,2),true)}</section><section><div className="section-heading"><h2>Seu tempo faz a diferença</h2><a href="#/voluntariado">Ver todas</a></div>{opportunities(db.opportunities.slice(0,1))}</section></>}
 else if(page==='doacoes'){body=<>{title('Minhas doações')}<ImpactStrip items={[[money(mineDon.reduce((a:number,d:any)=>a+d.amount,0)),'Total doado'],[mineDon.length,'Doações'],[new Set(mineDon.map((d:any)=>d.org)).size,'ONGs apoiadas']]}/><h2>Histórico de doações</h2>{history(mineDon)}{link('ongs','Fazer uma doação')}</>}
 else if(page==='meus-voluntariados'){const list=mineReg.filter((r:any)=>activityStatus==='all'||r.status===activityStatus);body=<>{title('Meus voluntariados')}<FilterChips label="Status do voluntariado" value={activityStatus} onChange={setActivityStatus} items={[{value:'all',label:'Todos'},{value:'Inscrito',label:'Inscritos'},{value:'Concluído',label:'Concluídos'},{value:'Encerrado',label:'Encerrados'}]}/>{list.length?list.map((r:any)=>{const v=db.opportunities.find((v:any)=>v.id===r.opportunity);return v?<OpportunityCard key={r.id} item={v} org={db.orgs.find((o:any)=>o.id===r.org)} registration={r}/>:null}):empty(activityStatus==='all'?'Seu próximo gesto começa aqui':'Nenhum voluntariado neste status')}{link('voluntariado','Encontrar voluntariado')}</>}
 else if(page==='perfil'){const rows=admin?[[UserRound,'Editar perfil','editar-perfil'],[LockKeyhole,'Alterar senha','senha'],[Building2,'Minha ONG','minha-ong'],[Heart,'Doações recebidas','recebidas'],[Users,'Voluntários inscritos','inscritos'],[Bell,'Notificações','notificacoes']]:[[UserRound,'Editar perfil','editar-perfil'],[LockKeyhole,'Alterar senha','senha'],[Bell,'Notificações','notificacoes'],[Heart,'Minhas doações','doacoes'],[Sprout,'Meus voluntariados','meus-voluntariados'],[Building2,'ONGs apoiadas','apoiadas']];body=<>{title('Meu perfil')}<div className="profile"><div className="avatar">{user.photo?<img src={user.photo} alt={user.name}/>:<UserRound size={46}/>}<a className="avatar-edit" href="#/editar-perfil" aria-label="Alterar foto"><Camera size={16}/></a></div><h2>{user.name}</h2><p>{user.email}<br/>{user.city}</p></div><div className="profile-menu">{rows.map(([Icon,t,p]:any)=><a className="menu-link" href={'#/'+p} key={p}><Icon size={20}/><span>{t}</span><ChevronRight size={16}/></a>)}<label className="menu-link notification-preference"><Bell size={20}/><span>Receber notificações</span><Switch checked={user.notifications!==false} onCheckedChange={v=>update((d:any)=>{d.session.notifications=v;const a=d.accounts.find((a:any)=>a.id===user.id);if(a)a.notifications=v;return d})}/></label><button className="menu-link logout-row" onClick={()=>{update((d:any)=>{d.session=null;return d});go('')}}><LogOut size={20}/><span>Sair</span></button></div></>}
 else if(page==='editar-perfil'||page==='senha'){body=<>{title(page==='senha'?'Alterar senha':'Editar perfil')}<Form key={route} initial={page==='senha'?{}:user} fields={page==='senha'?[field('password','Nova senha','password'),field('confirm','Confirmar senha','password')]:[field('name','Nome'),field('email','E-mail','email'),field('city','Cidade'),field('photo','Foto','file',true)]} onSubmit={async(v:any)=>{if(v.email&&db.accounts.some((a:any)=>a.id!==user.id&&a.email===v.email))throw Error('Este e-mail já está em uso.');update((d:any)=>{d.session={...d.session,...v};const a=d.accounts.find((a:any)=>a.id===user.id);if(a)Object.assign(a,v);return d});toast.success('Perfil atualizado');go('perfil')}}/></>}
 else if(page==='apoiadas'||page==='favoritas'){body=<>{title(page==='apoiadas'?'ONGs apoiadas':'ONGs favoritas')}{cards(db.orgs.filter((o:any)=>page==='favoritas'?db.favorites.includes(o.id):mineDon.some((d:any)=>d.org===o.id)))}</>}
 else if(page==='notificacoes'){const ns=db.notifications.filter((n:any)=>(n.owner===user.id||n.owner===user.org)&&(noticeType==='all'||(noticeType==='donation'?/doaç/i.test(n.text):/volunt|inscri|oportunidade/i.test(n.text))));body=<>{title('Notificações')}<FilterChips label="Tipo de notificação" value={noticeType} onChange={setNoticeType} items={[{value:'all',label:'Todas'},{value:'donation',label:'Doações'},{value:'volunteer',label:'Voluntariado'}]}/>{ns.length?<><button className="mark-read" onClick={()=>update((d:any)=>{d.notifications.forEach((n:any)=>{if(n.owner===user.id||n.owner===user.org)n.read=true});return d})}>Marcar todas como lidas</button>{ns.map((n:any)=><NoticeCard key={n.id} notice={n}/>)}</>:empty('Tudo em dia por aqui')}</>}
 else if(['painel','minha-ong','editar-ong','gerenciar','novo','editar','inscritos','recebidas'].includes(page)&&!admin){body=<>{title('Área da organização','Entre com uma conta de ONG para administrar seus projetos.')}{link('entrar','Entrar como ONG')}</>}
 else if(page==='painel'){const ds=db.donations.filter((d:any)=>d.org===own.id),rs=db.registrations.filter((r:any)=>r.org===own.id);body=<><span className="eyebrow">PAINEL DA ONG</span>{title('Olá, '+own.name+'!','Cada conexão faz sua causa ir mais longe.')}{stats([[money(ds.reduce((a:number,d:any)=>a+d.amount,0)),'Total recebido'],[ds.length,'Doações'],[db.projects.filter((p:any)=>p.org===own.id).length,'Projetos'],[db.needs.filter((p:any)=>p.org===own.id).length,'Necessidades'],[rs.length,'Voluntários']])}<h2>Ações rápidas</h2>{[['needs','Nova necessidade'],['projects','Novo projeto'],['opportunities','Nova oportunidade de voluntariado']].map(([p,t])=>link('novo/'+p,<><Plus size={18}/>{t}</>,'secondary'))}{link('editar-ong','Editar ONG','text-link')}<h2>Últimas doações</h2>{history(ds.slice(0,3))}<h2>Últimos voluntários</h2>{rs.length?rs.slice(0,3).map((r:any)=><div className="card" key={r.id}>{r.name} · {r.status}</div>):empty('Aguardando novos voluntários')}<h2>Projetos ativos</h2>{funding(db.projects.filter((p:any)=>p.org===own.id),'projects')}</>}
 else if(page==='minha-ong'){body=<>{title('Minha ONG')}<img className="auth-logo" src={own.image} alt={own.name}/><h2>{own.name}</h2><span className="tag">{own.category}</span><p>{own.city} · {own.district}</p><h3>História</h3><p>{own.history}</p><h3>Descrição</h3><p>{own.description}</p><h3>Missão</h3><p>{own.mission}</p>{link('editar-ong','Editar informações')}{link('ong/'+own.id,'Ver página pública','secondary')}</>}
 else if(page==='editar-ong'){body=<>{title('Editar minha ONG')}<Form key={route} initial={own} fields={[field('name','Nome da ONG'),field('city','Cidade'),field('district','Bairro'),{key:'category',label:'Categoria',options:categories},field('history','História','textarea'),field('description','Descrição','textarea'),field('mission','Missão','textarea'),field('image','Logo','file',true),field('cover','Capa','file',true)]} onSubmit={async(v:any)=>{update((d:any)=>{Object.assign(d.orgs.find((o:any)=>o.id===own.id),v);return d});toast.success('Informações atualizadas');go('minha-ong')}}/></>}
 else if(page==='gerenciar'){const type=['needs','projects','opportunities'].includes(id!)?id!:'needs';const names:any={needs:'Necessidades',projects:'Projetos',opportunities:'Oportunidades'};body=<>{title(names[type])}{link('novo/'+type,<><Plus size={18}/>Cadastrar {type==='projects'?'projeto':type==='needs'?'necessidade':'oportunidade'}</>)}{type==='opportunities'?<>{opportunities(db.opportunities.filter((v:any)=>v.org===own.id))}{link('inscritos','Ver voluntários inscritos','secondary')}</>:funding(db[type].filter((v:any)=>v.org===own.id),type)}</>}
 else if(page==='novo'||page==='editar'){const type=['needs','projects','opportunities'].includes(id!)?id!:'needs',vol=type==='opportunities',editing=page==='editar',record=editing?db[type].find((n:any)=>n.id===arg&&n.org===own.id):undefined;const fields=vol?[field('title','Título'),field('description','Descrição','textarea'),{key:'category',label:'Categoria',options:categories},field('date','Data','date'),field('time','Horário','time'),field('location','Local'),field('slots','Quantidade de vagas','number'),field('requirements','Requisitos','textarea')]:[field('title',type==='projects'?'Nome do projeto':'Título'),field('description','Descrição','textarea'),...(type==='projects'?[field('objective','Objetivo','textarea'),field('audience','Público beneficiado')]:[{key:'category',label:'Categoria',options:categories}]),field('goal','Valor necessário (R$)','number'),field('image','Imagem','file',true),field('deadline','Prazo','date')];body=editing&&!record?empty('Cadastro não encontrado nesta ONG'):<>{title(editing?(type==='projects'?'Editar projeto':'Editar necessidade'):vol?'Nova oportunidade':type==='projects'?'Novo projeto':'Nova necessidade')}<Form key={route} initial={record||{}} fields={fields} submit={editing?'Salvar alterações':vol?'Publicar oportunidade':type==='projects'?'Publicar projeto':'Publicar necessidade'} onSubmit={async(v:any)=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(v.date||v.deadline)||!Number.isFinite(Date.parse(v.date||v.deadline))||(v.date||v.deadline)<new Date().toISOString().slice(0,10))throw Error('Escolha uma data futura.');update((d:any)=>{if(editing){const item=d[type].find((n:any)=>n.id===arg&&n.org===own.id);if(!item)throw Error('Cadastro não encontrado.');Object.assign(item,v,{id:item.id,org:own.id,raised:item.raised,goal:Number(v.goal)||0,slots:Number(v.slots)||0});if(type==='projects')d.donations.filter((don:any)=>don.target===item.id).forEach((don:any)=>notify(d,'Atualização de projeto: '+v.title,don.user))}else d[type].push({...v,id:crypto.randomUUID(),org:own.id,raised:0,status:'Ativo',goal:Number(v.goal)||0,slots:Number(v.slots)||0});if(vol&&!editing)d.accounts.filter((a:any)=>a.role==='user').forEach((a:any)=>notify(d,'Nova oportunidade: '+v.title,a.id));return d});toast.success(editing?'Alterações salvas':'Publicado com sucesso');go('gerenciar/'+type)}}/></>}
 else if(page==='inscritos'){const rs=db.registrations.filter((r:any)=>r.org===own.id);body=<>{title('Voluntários inscritos')}{rs.length?rs.map((r:any)=><div className="card" key={r.id}><h2>{r.name}</h2><p>{db.opportunities.find((v:any)=>v.id===r.opportunity)?.title}</p><small>Inscrição em {r.date}</small><Choice label="Status" value={r.status} options={['Inscrito','Concluído','Encerrado']} onChange={(v:string)=>update((d:any)=>{d.registrations.find((x:any)=>x.id===r.id).status=v;return d})}/></div>):empty('Nenhum voluntário inscrito')}</>}
 else if(page==='recebidas'){const ds=db.donations.filter((d:any)=>d.org===own.id);body=<>{title('Doações recebidas')}{stats([[money(ds.reduce((a:number,d:any)=>a+d.amount,0)),'Total recebido'],[ds.length,'Doações'],[new Set(ds.filter((d:any)=>db.needs.some((n:any)=>n.id===d.target)).map((d:any)=>d.target)).size,'Necessidades apoiadas'],[new Set(ds.filter((d:any)=>db.projects.some((n:any)=>n.id===d.target)).map((d:any)=>d.target)).size,'Projetos apoiados']])}{history(ds)}</>}
 else{body=<>{title('Página não encontrada')}{link('','Voltar ao início')}</>}
 return <AppShell user={user} admin={admin} ready={ready} route={route} notifications={db.notifications}>
  {body}
 </AppShell>
}



