"use client";
import {Heart,MapPin,CalendarDays,HandHeart,Clock,ChevronRight,Leaf,UserRound,ArrowLeft,Check,Copy,QrCode} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
export const donationCode='SETHO-DEMONSTRACAO-SEM-VALOR-DE-PAGAMENTO';
export function CauseBadge({children}:any){return <span className="cause-badge">{children}</span>}
export function OrganizationIdentity({org,small=false}:any){return <div className={'organization-identity '+(small?'small':'')}><img src={org.image||'/setho.jpeg'} alt=""/><div><h3>{org.name}</h3><p><MapPin size={12}/>{org.city}{org.district?' · '+org.district:''}</p><CauseBadge>{org.category}</CauseBadge></div></div>}
export function OrganizationCard({org,favorite,onFavorite,compact=false}:any){return <article className={'organization-card '+(compact?'compact':'')}><div className="organization-top"><div className="organization-thumb"><img src={org.cover||'/community.jpg'} alt=""/><img className="thumb-mark" src={org.image||'/setho.jpeg'} alt=""/></div><div className="organization-caption"><h3>{org.name}</h3><p><MapPin size={12}/>{org.city} · {org.district}</p><CauseBadge>{org.category}</CauseBadge></div>{!compact&&<button className="favorite-button" aria-label={favorite?'Remover ONG dos favoritos':'Favoritar ONG'} aria-pressed={favorite} onClick={onFavorite}><Heart size={17} fill={favorite?'currentColor':'none'}/></button>}</div>{!compact&&<p className="org-description">{org.description}</p>}<a className="primary" href={'#/ong/'+org.id}>Ver ONG</a></article>}
export function OpportunityCard({item,org,available,registration}:any){return <article className="opportunity-card"><div className="organization-top"><div className="opportunity-thumb"><img src={item.image||org?.cover||'/community.jpg'} alt=""/></div><div className="opportunity-caption"><h3>{item.title}</h3><p><Leaf size={12}/>{org?.name}</p><p><CalendarDays size={12}/>{new Date(item.date+'T12:00:00').toLocaleDateString('pt-BR')} · {item.time}</p>{registration?<span className={'status-badge status-'+registration.status.toLowerCase()}>{registration.status}</span>:<><p><MapPin size={12}/>{org?.city}</p><p><HandHeart size={12}/>{available} vagas disponíveis</p></>}</div></div><a className={registration?'detail-link':'primary'} href={'#/oportunidade/'+item.id}>{registration?'Ver detalhes':'Ver oportunidade'}{registration&&<ChevronRight size={15}/>}</a></article>}
export function FilterChips({value,onChange,items,label}:any){return <Tabs value={value} onValueChange={onChange} className="filter-chips"><TabsList aria-label={label}>{items.map((i:any)=><TabsTrigger key={i.value} value={i.value}>{i.label}</TabsTrigger>)}</TabsList></Tabs>}
export function ImpactStrip({items}:any){return <div className="impact-strip">{items.map(([value,label]:any)=><div key={label}><b>{value}</b><span>{label}</span></div>)}</div>}
export function DonationHistoryCard({donation,org,money}:any){return <article className="donation-history-card"><img src={org?.image||'/setho.jpeg'} alt=""/><div><h3>{org?.name}</h3><p><Leaf size={13}/>{donation.targetTitle||'Apoio à organização'}</p><p><CalendarDays size={13}/>{money(donation.amount)} · {donation.date}</p><span className="status-badge">Concluída</span></div></article>}
export function NoticeCard({notice}:any){const donation=/doaç/i.test(notice.text),volunteer=/volunt|inscri|oportunidade/i.test(notice.text);const Icon=donation?Heart:volunteer?HandHeart:Leaf;return <article className={'notice-card '+(!notice.read?'is-new':'')}><span className={'notice-icon '+(donation?'coral':'')}><Icon size={21}/></span><div><h3>{donation?'Doação confirmada':/oportunidade/i.test(notice.text)?'Nova oportunidade':volunteer?'Voluntariado':'Atualização de projeto'}</h3><p>{notice.text}</p><small>{notice.date}</small></div>{!notice.read&&<span className="unread-dot" aria-label="Não lida"/>}</article>}
